FROM docker.io/osrf/ros:humble-desktop-full-jammy

RUN apt update && \
    apt install -y \
        ros-humble-teleop-twist-joy \
        ros-humble-navigation2 \
        ros-humble-nav2-bringup \
        ros-humble-slam-toolbox \
        ros-humble-rmw-cyclonedds-cpp && \
    rm -rf /var/lib/apt/lists/*a

RUN mkdir /workspace

WORKDIR /workspace

ENTRYPOINT ["/ros_entrypoint.sh"]
